services:
  dnmonster:
    image: amouat/dnmonster:1.0
  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENV=DEV
    volumes:
      - ./app:/app
    links:
      - dnmonster
      - redis
  redis:
    image: redis:3.2

