services:
  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - jenkins_network
      
  identidock:
    build: .
    expose:
      - "9090"
      - "9191"
    environment:
      - ENV=PROD
    depends_on:
      - dnmonster
      - redis
    networks:
      - jenkins_network
      
  redis:
    image: redis:3.2
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge

